version: '3'
services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 8080:80
    volumes:
      - client_node_modules:/app/node_modules
      - ./client:/app
volumes:
  client_node_modules: